//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace Cfg.Demo
{

public sealed partial class AIMeta :  Bright.Config.BeanBase 
{
    public AIMeta(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Order = _buf.ReadInt();
        Name = _buf.ReadString();
        {int n = System.Math.Min(_buf.ReadSize(), _buf.Size);NodeParams = new System.Collections.Generic.List<int>(n);for(var i = 0 ; i < n ; i++) { int _e;  _e = _buf.ReadInt(); NodeParams.Add(_e);}}
        PostInit();
    }

    public static AIMeta DeserializeAIMeta(ByteBuf _buf)
    {
        return new Demo.AIMeta(_buf);
    }

    public int Id { get; private set; }
    public int Order { get; private set; }
    public string Name { get; private set; }
    public System.Collections.Generic.List<int> NodeParams { get; private set; }

    public const int __ID__ = 233945240;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Order:" + Order + ","
        + "Name:" + Name + ","
        + "NodeParams:" + Bright.Common.StringUtil.CollectionToString(NodeParams) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
