//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace Cfg.Demo
{
   
public partial class TbStartZoneConfig
{
    private readonly Dictionary<int, Demo.StartZoneConfig> _dataMap;
    private readonly List<Demo.StartZoneConfig> _dataList;
    
    public TbStartZoneConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Demo.StartZoneConfig>();
        _dataList = new List<Demo.StartZoneConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Demo.StartZoneConfig _v;
            _v = Demo.StartZoneConfig.DeserializeStartZoneConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Demo.StartZoneConfig> DataMap => _dataMap;
    public List<Demo.StartZoneConfig> DataList => _dataList;

    public Demo.StartZoneConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Demo.StartZoneConfig Get(int key) => _dataMap[key];
    public Demo.StartZoneConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}